name: docker

# Make this workflow run only on default branch and tagged branches and after the 'stable' workflow has passed
on:
  workflow_run:
    workflows: [ stable ]
    types: [ completed ]
#    branches: [ $default_branch ]
#    tags: [ "**" ]
  workflow_dispatch:

jobs:
  deploy:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        configuration:
          - dockerfile: "Dockerfile"
            repository: "tiledb/tiledb-maria"
#          - dockerfile: "Dockerfile-min"
#            repository: "tiledb/tiledb-maria-min"
#          - dockerfile: "Dockerfile-server"
#            repository: "tiledb/tiledb-maria-server"
#          - dockerfile: "Dockerfile-R"
#            repository: "tiledb/tiledb-maria-r"
    steps:
      - uses: actions/checkout@v3
#      - uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ matrix.configuration.repository }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.configuration.dockerfile }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MYTILE_VERSION=${{ github.ref_name }}
            GITHUB_USER=${{ github.actor }}
