name: docker

# TODO: In the future make this workflow_run, however, that one does not support tags only branches
# TODO: Or make this take a list of tags... Sadly this cannot be done now, only string can be passed
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        configuration:
          - dockerfile: "Dockerfile"
            repository: "tiledb/tiledb-maria"
          - dockerfile: "Dockerfile-min"
            repository: "tiledb/tiledb-maria-min"
          - dockerfile: "Dockerfile-server"
            repository: "tiledb/tiledb-maria-server"
          - dockerfile: "Dockerfile-R"
            repository: "tiledb/tiledb-maria-r"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push develop
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        with:
          context: .
          file: docker/${{ matrix.configuration.dockerfile }}
          push: true
          tags: |
            ${{ matrix.configuration.repository }}:dev
          build-args: |
            MYTILE_VERSION=${{ github.ref_name }}
      - name: Build and push release
        uses: docker/build-push-action@v5
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          context: .
          file: docker/${{ matrix.configuration.dockerfile }}
          push: true
          tags: |
            ${{ matrix.configuration.repository }}:latest
            ${{ matrix.configuration.repository }}:${{ github.ref_name }}
          build-args: |
            MYTILE_VERSION=${{ github.ref_name }}
