name: docker

# Make this workflow run only on default branch and tagged branches and after the 'stable' workflow has passed
on:
  workflow_run:
    workflows: [ stable ]
    branches: [ $default_branch ]
    tags: [ '**' ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dockerfile: ["Dockerfile", "Dockerfile-min", "Dockerfile-server", "Dockerfile-R"]
    steps:
      - uses: actions/checkout@v3
      #      - uses: docker/login-action
      #        with:
      #          username: {{}}
      #          password: {{}}
      - uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/${{ matrix.dockerfile }}
          push: false
