name: stable
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: stable-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-13", "ubuntu-22.04"]
    env:
      OWNER_TILEDB_MARIADB: ${{ github.repository_owner }} # support building from a fork
      REF_MARIADB: mariadb-11.0.2
      REF_LIBTILEDB: dev
      REF_TILEDB_MARIADB: ${{ github.sha }}
      TILEDB_FORCE_ALL_DEPS: OFF
    steps:
      - uses: actions/checkout@v3
      - name: Clone and checkout repos
        run: bash scripts/nightly/checkout.sh
      - name: Setup Ubuntu
        if: runner.os == 'Linux'
        run: sudo bash scripts/nightly/setup-ubuntu.sh
      - name: Setup macOS
        if: runner.os == 'macOS'
        run: bash scripts/nightly/setup-macos.sh
      - name: Build libtiledb
        run: bash scripts/nightly/build-libtiledb.sh
      - name: Build TileDB-MariaDB
        run: bash scripts/nightly/build-tiledb-mariadb.sh
