name: stable
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: stable-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-13", "ubuntu-22.04"]
    env:
      OWNER_TILEDB_MARIADB: ${{ github.repository_owner }} # support building from a fork
      REF_MARIADB: mariadb-11.0.2
      REF_LIBTILEDB: 2.18.0
      REF_TILEDB_MARIADB: ${{ github.sha }}
      TILEDB_FORCE_ALL_DEPS: OFF
    steps:
      # This initial checkout is only to obtain the CI scripts
      - uses: actions/checkout@v3
      - name: Clone and checkout repos
        run: bash scripts/ci/checkout.sh
      - name: Setup Ubuntu
        if: runner.os == 'Linux'
        run: sudo bash scripts/ci/setup-ubuntu.sh
      - name: Setup macOS
        if: runner.os == 'macOS'
        run: bash scripts/ci/setup-macos.sh
      - name: Build libtiledb
        run: bash scripts/ci/build-libtiledb.sh
      - name: Build TileDB-MariaDB
        run: bash scripts/ci/build-tiledb-mariadb.sh

  deploy:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') || github.ref_name == 'master' }}
    needs: [build]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dockerfile: ["Dockerfile", "Dockerfile-min", "Dockerfile-server", "Dockerfile-R"]
    steps:
      - uses: actions/checkout@v3
#      - uses: docker/login-action
#        with:
#          username: {{}}
#          password: {{}}
      - uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/${{ matrix.dockerfile }}
          push: false
